name: iksha_driver
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.4
  dio: ^5.3.4
  get: 4.6.6
  cached_network_image: ^3.3.0
  font_awesome_flutter: ^10.6.0
  otp_text_field: ^1.1.3
  google_maps_flutter: ^2.5.0

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/images/tracking.png

  uses-material-design: true

